from pydantic import BaseModel, Field
from nested.message_result import MessageResult

# TODO: Why is stream response for /chat API so much lighter than for /generate in Ollama?
class ChatResponseNdjson(BaseModel):
    """ Response model for application/x-ndjson response format for `/chat` API """

    model: str = Field()
    """ Model name """
    
    created_at: str = Field()
    """ ISO 8601 timestamp of response creation """

    message: MessageResult
    """ Message generated by model """

    done: bool = Field()
    """ Indicates whether generation has finished """
